version: '3.8'

services:
  bot-nc:
    build: .
    container_name: bot_nc_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
