networks:
  icontainer-network:
    external: true

services:
  bot-nc:
    image: ghcr.io/kasuminho/sistemas-aviso-discord-nc:latest
    container_name: bot-nc
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    env_file:
      - icontainer.env
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
    networks:
      - icontainer-network
    volumes:
      - /srv/bot-nc/data:/app/data
